// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5YutOOK3nEj6kBFLC2EH2uTKRJ03olNw',
    appId: '1:98494694512:web:28fa0f8db3250b9e8c20b5',
    messagingSenderId: '98494694512',
    projectId: 'timecraft-1cbe5',
    authDomain: 'timecraft-1cbe5.firebaseapp.com',
    storageBucket: 'timecraft-1cbe5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgmfn4OfIv1fGw1_kxXWpN6FK01zrPO68',
    appId: '1:98494694512:android:546302736fd19b768c20b5',
    messagingSenderId: '98494694512',
    projectId: 'timecraft-1cbe5',
    storageBucket: 'timecraft-1cbe5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs1ZNyGpLbTlYkJL919zJzfK1IwPuZFdg',
    appId: '1:98494694512:ios:25a8d5fe921212c98c20b5',
    messagingSenderId: '98494694512',
    projectId: 'timecraft-1cbe5',
    storageBucket: 'timecraft-1cbe5.firebasestorage.app',
    iosBundleId: 'com.example.timecraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs1ZNyGpLbTlYkJL919zJzfK1IwPuZFdg',
    appId: '1:98494694512:ios:25a8d5fe921212c98c20b5',
    messagingSenderId: '98494694512',
    projectId: 'timecraft-1cbe5',
    storageBucket: 'timecraft-1cbe5.firebasestorage.app',
    iosBundleId: 'com.example.timecraft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5YutOOK3nEj6kBFLC2EH2uTKRJ03olNw',
    appId: '1:98494694512:web:6cf3c3f9e33a373d8c20b5',
    messagingSenderId: '98494694512',
    projectId: 'timecraft-1cbe5',
    authDomain: 'timecraft-1cbe5.firebaseapp.com',
    storageBucket: 'timecraft-1cbe5.firebasestorage.app',
  );
}
